export * from './BoxStock'
export * from './FacturasRecientes'
export * from './VentasRecientes'
export * from './MenuPages'
export * from './NuevaVenta'
export * from './TopCompradores'
export * from './Stock'